# Generated by Django 5.1.1 on 2024-09-17 18:23

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioPSQI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Questionário PSQI', max_length=255)),
                ('descricao', models.TextField(default='Por favor, responda às perguntas abaixo para avaliar a qualidade do seu sono.')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('data_nascimento', models.DateField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RespostaPSQI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateField(default=datetime.date.today, editable=False)),
                ('pergunta_1', models.IntegerField()),
                ('pergunta_2', models.IntegerField()),
                ('pergunta_3', models.IntegerField()),
                ('pergunta_4', models.IntegerField()),
                ('pergunta_5a', models.IntegerField()),
                ('pergunta_5b', models.IntegerField()),
                ('pergunta_5c', models.IntegerField()),
                ('pergunta_5d', models.IntegerField()),
                ('pergunta_5e', models.IntegerField()),
                ('pergunta_5f', models.IntegerField()),
                ('pergunta_5g', models.IntegerField()),
                ('pergunta_5h', models.IntegerField()),
                ('pergunta_5i', models.IntegerField()),
                ('pergunta_5ja', models.TextField()),
                ('pergunta_5jb', models.IntegerField()),
                ('pergunta_6', models.IntegerField()),
                ('pergunta_7', models.IntegerField()),
                ('pergunta_8', models.IntegerField()),
                ('pergunta_9', models.IntegerField()),
                ('pergunta_10', models.IntegerField()),
                ('formulario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='app.formulariopsqi')),
                ('usuario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
